In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9853, 260, 3625, 4580],
 [9853, 260, 3625, 11],
 [9853, 785, 3625, 2345],
 [2372, 186, 7119, 7340, 6990],
 [2372, 186, 7119, 7340, 6219],
 [449, 9853, 4510, 3625, 7491],
 [1200, 6628, 7447, 7340]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9853  260 3625 4580]
 [   0    0    0    0 9853  260 3625   11]
 [   0    0    0    0 9853  785 3625 2345]
 [   0    0    0 2372  186 7119 7340 6990]
 [   0    0    0 2372  186 7119 7340 6219]
 [   0    0    0  449 9853 4510 3625 7491]
 [   0    0    0    0 1200 6628 7447 7340]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[[ 0.02242551,  0.02497957, -0.03473592, -0.02115737,
          0.04795447,  0.01139813, -0.03389149,  0.0075451 ,
         -0.04435864, -0.02053872],
        [ 0.02242551,  0.02497957, -0.03473592, -0.02115737,
          0.04795447,  0.01139813, -0.03389149,  0.0075451 ,
         -0.04435864, -0.02053872],
        [ 0.02242551,  0.02497957, -0.03473592, -0.02115737,
          0.04795447,  0.01139813, -0.03389149,  0.0075451 ,
         -0.04435864, -0.02053872],
        [ 0.02242551,  0.02497957, -0.03473592, -0.02115737,
          0.04795447,  0.01139813, -0.03389149,  0.0075451 ,
         -0.04435864, -0.02053872],
        [ 0.0214205 , -0.03735643,  0.0189845 ,  0.00950005,
         -0.01969501, -0.0061079 ,  0.0253568 ,  0.01294697,
          0.01558912,  0.03378348],
        [-0.0192007 , -0.03708471,  0.01968316,  0.04995939,
         -0.03781375, -0.01066483,  0.00181819, -0.00531769,
          0.04615562,  0.01466645],
        [ 0.00852426,  0.00877073, -0.04405056,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9853,  260, 3625, 4580], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None